// Generated by ProtoGen, Version=2.4.1.521, Culture=neutral, PublicKeyToken=55f7125234beb589.  DO NOT EDIT!
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.ProtocolBuffers;
using pbc = global::Google.ProtocolBuffers.Collections;
using pbd = global::Google.ProtocolBuffers.Descriptors;
using scg = global::System.Collections.Generic;
namespace OpenApiLib {
  
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  public static partial class CommonModelMessages {
  
    #region Extension registration
    public static void RegisterAllExtensions(pb::ExtensionRegistry registry) {
    }
    #endregion
    #region Static variables
    #endregion
    #region Descriptor
    public static pbd::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbd::FileDescriptor descriptor;
    
    static CommonModelMessages() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          "ChlDb21tb25Nb2RlbE1lc3NhZ2VzLnByb3RvKiMKDlByb3RvVHJhZGVTaWRl" + 
          "EgcKA0JVWRABEggKBFNFTEwQAipVChBQcm90b1RpbWVJbkZvcmNlEhIKDkdP" + 
          "T0RfVElMTF9EQVRFEAESFAoQR09PRF9USUxMX0NBTkNFTBACEhcKE0lNTUVE" + 
          "SUFURV9PUl9DQU5DRUwQA0JPCipjb20ueHRyYWRlci5wcm90b2NvbC5wcm90" + 
          "by5jb21tb25hcGkubW9kZWxCHENvbW1vbkNvbnRhaW5lck1vZGVsTWVzc2Fn" + 
          "ZXNQAaABAQ==");
      pbd::FileDescriptor.InternalDescriptorAssigner assigner = delegate(pbd::FileDescriptor root) {
        descriptor = root;
        return null;
      };
      pbd::FileDescriptor.InternalBuildGeneratedFileFrom(descriptorData,
          new pbd::FileDescriptor[] {
          }, assigner);
    }
    #endregion
    
  }
  #region Enums
  public enum ProtoTradeSide {
    BUY = 1,
    SELL = 2,
  }
  
  public enum ProtoTimeInForce {
    GOOD_TILL_DATE = 1,
    GOOD_TILL_CANCEL = 2,
    IMMEDIATE_OR_CANCEL = 3,
  }
  
  #endregion
  
}

#endregion Designer generated code
